from .authentication_views import *
from .lesson_views import *
from .transfer_views import *
from .administrator_views import *
from .child_views import *
from .term_views import *
from .school_views import *
from .director_views import *
from .teacher_view import *
from .timetable_views import *