# Generated by Django 4.1.3 on 2022-11-13 00:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_availableday_alter_user_email_alter_user_name_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='availability',
        ),
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='from_hour',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lesson',
            name='to_hour',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='AvailableDay',
        ),
    ]
