# Generated by Django 4.1.3 on 2022-11-13 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_lesson_availability_lesson_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='from_hour',
            new_name='hour',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='to_hour',
        ),
    ]
