# Generated by Django 4.1.3 on 2022-11-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.TextField(default='Title', max_length=20),
        ),
    ]
